### ISSUE TITLE
handle 'chr' prefix

### ISSUE THREAD

**Issue by brentp** [brentp/peddy#15]
currently, if the query vcf has 'chr' prefixes, then none of the variants will be found. I think the best solution is a --strip-chr flag that will remove the 'chr' prefix if it is found. 

Could also check the sites and see that they don't have 'chr' and then strip 'chr' if it is found in the query.

**Comment by brentp** [comment]
this is implemented and tested in the notebook branch.

**Comment by brentp** [comment]
![peddy-final-copy](https://cloud.githubusercontent.com/assets/1739/21734388/5a927926-d420-11e6-8ff9-534046df3305.png)

**Comment by joonan30** [comment]
Hi Brent, 

Is this option working for the current version? `--strip-chr` 

I met the issue with `chr` prefix VCF. Do you have any option for this?

Thanks,
