### ISSUE TITLE
can you use `https://cdn.plot.ly/plotly-latest.min.js` for plotly

### ISSUE THREAD

**Issue by leipzig** [brentp/peddy#22]
`http://cdn.plot.ly/plotly-latest.min.js` produces a mixed content error in modern browsers

Mixed Content: The page at ...was loaded over HTTPS, but requested an insecure script 'http://cdn.plot.ly/plotly-latest.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by brentp** [comment]
this has been in place for some time:
https://github.com/brentp/peddy/commit/248b6d950473dde5e1ef9cdf2621916a1717b21a
can you update to the latest version? v0.2.9
