### ISSUE TITLE
Only plot PCA from cohort without doing any other analysis

### ISSUE THREAD

**Issue by snashraf** [brentp/peddy#24]
Hi brent,

Maybe you add an option to just plot PCA from cohort without doing any other analysis? I have a cohort of few hundreds of exomes and wanted to plot PCA wth 1K Genome data and not willing to do any other analysis, so if you add a simple option of doing that ( preferably if without even making that ped file as well ) 

Thanks
Najeeb

**Comment by brentp** [comment]
I don't have plans to do that but you could call the pca() function in peddy yourself if you want to use it externally.

You can create a ped file from a vcf with a simple command:

```
 zgrep -m1 "^#CHROM" $vcf | cut -f 10- | perl -pe 's/\t/\n/g' \
    | awk 'BEGIN{FS="\t"}{ print "fam"NR"\t"$1"\t-9\t-9\t-9\t1" }
```

**Comment by snashraf** [comment]
Thanks Brent !! No issue !! I will manage with Peddy only !!
