### ISSUE TITLE
X server dependency error

### ISSUE THREAD

**Issue by henrikstranneheim** [brentp/peddy#29]
Is it possible to run peddy without the X server dependency?

I get this error when running:
```
$python -m peddy --version --procs 4 --plot --prefix peddy/118 in.vcf.gz 118.fam
$: cannot connect to X server
```

**Comment by brentp** [comment]
hmm, it should not require X server as it is using Agg. Can you try:

```
export MPLBACKEND=Agg
python -m peddy --version --procs 4 --plot --prefix peddy/118 in.vcf.gz 118.fam
```
and see if that does it?

**Comment by henrikstranneheim** [comment]
I added this to the bash script that runs peddy, but it produces the same error.

**Comment by henrikstranneheim** [comment]
However, It does not seem that i have Agg installed. Should it have been shipped with the bioconda install?

**Comment by brentp** [comment]
maybe remove the --version, that flag isn't supported anyway. Are you using the version from github or what version? We had some recent changes but I still can't re-create this.

**Comment by brentp** [comment]
seems like it might be related to this: https://github.com/matplotlib/matplotlib/issues/6418
you're on linux, yes?

**Comment by henrikstranneheim** [comment]
Sorry, about that. The --version flag is not included in what I have been running.

I installed peddy 0.2.9 using bioconda.

yes, I am on linux

**Comment by brentp** [comment]
so can you run:
```
python -c "import matplotlib; print(matplotlib)"
```
and make sure you are getting the module from bioconda and not a system module?
otherwise, I'm out of ideas.

**Comment by henrikstranneheim** [comment]
```
$python -c "import matplotlib; print(matplotlib)"
<module 'matplotlib' from '/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/matplotlib/__init__.pyc'>
```

Was that the intended output? Unfortunately, still the same error.

**Comment by henrikstranneheim** [comment]
Peddy works fine on our login node, it is when i distribute this to the nodes in the cluster that it generates this error.

**Comment by brentp** [comment]
can you submit a job that shows the matplotlib path then? and make sure it's the same.

**Comment by henrikstranneheim** [comment]
Login: <module 'matplotlib' from '/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/matplotlib/__init__.pyc'>
Node: <module 'matplotlib' from '/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/matplotlib/__init__.pyc'>

**Comment by brentp** [comment]
I am out of ideas. I guess you could just make sure that Agg is working on your matplotlib module on the head node and on the worker nodes.

**Comment by henrikstranneheim** [comment]
OK, thx.

**Comment by henrikstranneheim** [comment]
If I install peddy in the basic conda installation without using an "env", I do not get the error on X server. So, it seems to be related to either installing peddy in a conda env or sourcing that env on the node. 

Anyhow, I should be able to use this workaround. Thx for your time.

**Comment by brentp** [comment]
odd. thanks for figuring it out.
