### ISSUE TITLE
question about PCA plot

### ISSUE THREAD

**Issue by liushuangmms** [brentp/peddy#32]
Sometimes the pc2 flipped in the plot (top plot). Since the data are projected to the same reference panel, should the backgroud PC2 vs. PC1 pattern in the plot always be the same? Please see the attached plot:
![hbcc_2 pca pca_check](https://user-images.githubusercontent.com/11318599/30564707-d5e105b6-9c93-11e7-9fa4-82607c6f8bc1.png)
![hbcc_3 pca pca_check](https://user-images.githubusercontent.com/11318599/30564745-f4af19f6-9c93-11e7-99ff-48cbe383afdf.png)

**Comment by brentp** [comment]
This can happen becuase of the meaning of the PCA: https://stats.stackexchange.com/questions/88880/does-the-sign-of-scores-or-of-loadings-in-pca-or-fa-have-a-meaning-may-i-revers

**Comment by liushuangmms** [comment]
Got it! Almost forgot about this meaning. Thanks very much!
