### ISSUE TITLE
support for hg38 and single chromosome 

### ISSUE THREAD

**Issue by joonan30** [brentp/peddy#33]
Hi Brent,

Thanks for the tool. I am wondering whether peddy support hg38 for PCA or other functions. 

Also, is there a way to use peddy on a single chromosome? This wouldn't make sense for some functions, but would be useful to do quick check on chr22 from a large VCF. 

Best,

**Comment by brentp** [comment]
most of the work for supporting hg38 would be to lift these: https://github.com/brentp/peddy/blob/master/peddy/1kg.sites
from GRch37 to hg38

**Comment by joonan30** [comment]
Thanks!

**Comment by roryk** [comment]
Hi Brent,

What is the format of the `1kg.sites.bin.gz` file? I lifted over the 1kg sites from hg19 to hg38 and added support for specifying using them, and that's the last part that is missing.

**Comment by brentp** [comment]
@roryk good timing. there's a grad student from Aaron's lab working on this literally right now. 

the 1kg.sites.bin.gz file is a flat binary array that you can read as:

```Python
tmp = np.fromstring(gzip.open(f, 'rb').read(), dtype=np.uint8).astype(np.int32)
genos1kg = tmp.reshape((23556, int(len(tmp) / 23556))).T
```

where 23556 is the number if sites used by peddy. I'll CC Mike as soon as I know his github username so he can chime in with his progress.

His plan is to lift the sites, exclude any that don't map from the 23556 and create a new .bin file. If, for example 23000+ map to hg38, then we'll just subset .sites.bin.gz to those that map to hg38 so we don't need 2 bin files.

**Comment by brentp** [comment]
it's @mikecormier working on this.

**Comment by roryk** [comment]
```
mkdir -p liftover
cd liftover
rm *.sites *.bed *.chain *.gz
wget http://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz
gunzip hg19ToHg38.over.chain.gz
cp ../peddy/sites/hg19/1kg.sites hg19.sites
sed -e 's/:/ /g' hg19.sites | awk '{print "chr"$1,$2-1,$2,$3,$4}' > hg19.bed
liftOver hg19.bed hg19ToHg38.over.chain hg38.bed unmapped.bed
cut -f1,3,4 -d " " hg38.bed | sed -e 's/	/:/g' | sed -e 's/chr//g' > hg38.sites
cd ..
```
@mikecormier, here is what I did to do the conversions, if that helps at all.

**Comment by brentp** [comment]
thanks @roryk . how many sites were not mapped?

**Comment by roryk** [comment]
96. I pushed the WIP branch for hg38-support (https://github.com/roryk/peddy/tree/hg38-support), I just added a --build option and moved the .sites files to `sites/${build}`.

**Comment by brentp** [comment]
thank you. there's a --sites option already that Mike is going to utilize (after making it work fully) so we don't need the build option.

once this first part is done, the plan is to also use some machine learning to optimize the sites (instead of  using the ~23K sites that I chose without much thought) so we should have better relatedness estimates out soon too.

**Comment by roryk** [comment]
Awesome. Thanks!

**Comment by chapmanb** [comment]
Brent, Mike and Rory -- I wanted to ping and see where this is at. We've integrated peddy into bcbio and folks are liking it so much they're now missing the reports on hg38 builds. Is there anything we can do to help finalize build 38 support? Thanks so much for peddy and all your work on it.

**Comment by brentp** [comment]
Hi All. @mikecormier has this working for hg38.

Concurrently, he's trying to improve the selection of sites that peddy samples so we get a better estimate of relatedness. Give us a couple more weeks and we'll make a release with what is then the best set.

Glad to hear there's demand for this.

**Comment by chapmanb** [comment]
Brilliant, thanks for working on this. Looking forward to testing it out when it's ready.

**Comment by ohofmann** [comment]
I'll echo that request :-) With PCGR moving to hg38 we are finally ready to switch over.

**Comment by brentp** [comment]
Mike is preparing a PR. I believe it should be ready soon.

**Comment by brentp** [comment]
@mikecormier is still working on the PR. This will include a new sites and bin.gz for both hg38 and hg37 that he has found to work well. The PR will include a metric and visualization of the new changes vs latest master for observed vs expected relatedness.
Once this is merged the new release will allow specifying `--sites hg38.sites` (or something similar) for peddy to work on hg38.

**Comment by brentp** [comment]
hg38 support is out.
