### ISSUE TITLE
Sex check error

### ISSUE THREAD

**Issue by nskbe** [brentp/peddy#36]
I'm running peddy on a vcf created by plink. I had to "manually" change chromosome 25 to X to make sex check work and I get no errors now. But no sex is determined for any of my 96 samples. In the HTML, sex_check = TRUE for all samples.
How can I troubleshoot or make sex check work?
The output is here:
https://www.dropbox.com/s/1j1s5xny4uswprt/peddy.tgz?dl=0
Thanks.
I'm running 0.3.1.
Edit: plink predicts sex correctly for almost all samples, misses 9 (that's why I'm trying peddy)

**Comment by brentp** [comment]
some software refuses to call hets in males on the X chromosome. This is understandable, but it doesn't work for how peddy infers sex. I assume that whatever you are giving peddy doesn't allow HET calls on the X.

**Comment by brentp** [comment]
closing this. if you can provide more information or a test-case, feel free to re-open.
