### ISSUE TITLE
Perform only ancestry-determination for sinlge sample

### ISSUE THREAD

**Issue by imgag** [brentp/peddy#47]
Hi,

I tested peddy and it was basically the only tool for ancestry-determination that works out-of-the-box.
Great work!

However I am only interested in ancestry determination and nothing else.
Is is possible to skip the rest of the checks?

We are doing diagnostics and typically process single samples not families - as do most diagnostics labs.
Is it possible to hand over only a VCF.GZ file and skip the PED file somehow?

Best,
  Marc

**Comment by brentp** [comment]
peddy should run on a single sample, no?
 
If you really don't want to run the other stuff, you can do something like:

```
import peddy

df, background_df = peddy.Ped('some.ped').het_check('some.vcf.gz')
```

but then you have to figure out how to plot / use those pandas dataframes.

**Comment by imgag** [comment]
I'll try that. Thanks for the hint.
