### ISSUE TITLE
peddy warning sampleID with leading zero

### ISSUE THREAD

**Issue by Fazulur** [brentp/peddy#52]
Dear Peddy team,

bcbio_nextgen wes pipeline is runnig peddy as part of QC and here is the command

peddy --plot -p 4 --prefix test 02003-effects-annotated-filterSNP-filterINDEL.vcf.gz 02003-effects-annotated-filterSNP-filterINDEL.ped

Warning message

2018-11-18 09:04:04 ngslogin1 peddy.cli[13805] INFO Running Peddy version 0.4.2
2018-11-18 09:04:04 ngslogin1 peddy.cli[13805] WARNING 1 samples in vcf not in ped:
02003

2018-11-18 09:04:04 ngslogin1 peddy.cli[13805] WARNING 1 samples in ped not in vcf:
2003

I observed that it is ignoring leading zero from .ped file.
Is there any way to make peddy not to ignore leading zero's from sampleID field of .ped file.
Please suggest me?

Thanks In Advance
Fazulur Rehaman

**Comment by brentp** [comment]
Hi, I just pushed a fix for this. I'll make a new peddy release shortly. Thanks for reporting.

**Comment by Fazulur** [comment]
Hi Brent,

Thanks a lot for your quick response and fix.

Thanks & Regards
Fazulur Rehaman
