### ISSUE TITLE
How to pass stdin for VCF input?

### ISSUE THREAD

**Issue by FrankFeng** [brentp/peddy#60]
Hi,

I tried passing "-" and "/dev/stdin" for VCF input, but it gave me this error message: "IOError: /dev/stdin if not valid bcf or vcf".

Sometimes I need to do some filtering for the VCF file before passing it to peddy. It would be great if peddy can accept stdin for VCF input. Thanks!

Best,
Frank

**Comment by brentp** [comment]
peddy uses the index to extract specific variants. it can't do that for stdin.
