### ISSUE TITLE
mean depth is OK, but median depth is -2 for all sample

### ISSUE THREAD

**Issue by wym0072003** [brentp/peddy#66]
As the title, for my 100 WGS samples, the mean depth in peddy.het_check.csv is ~ 10, but all median depth are -2. Meanwhile, the hom_ref_count is 0 for all sample in sex_check_new.csv. What's the possible reason causes these issues? Thanks.

**Comment by brentp** [comment]
can you share the html output via email? that will help me to determine what is happening.

**Comment by brentp** [comment]
were these samples called individually and then the VCFs merged after? if so, don't expect peddy, or any tool to work properly.

**Comment by wym0072003** [comment]
Yes, it is merged VCF. Why peddy is not available for merged file? 
I found it might work on merged vcf when setting missing variants as homo REF.
I will email you html later, thank you.
