### ISSUE TITLE
Is Grch38 with chr prefix supported

### ISSUE THREAD

**Issue by henrikstranneheim** [brentp/peddy#67]
Thx for a great software!

I am processing a vcf with peddy version 0.4.3 with the following contigs for grch38:
```
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
```
Peddy has the option `--sites hg38`, but that means that peddy will use the git repo shipped file with no chromosome prefix. 

Will peddy work with the contigs in my vcf which has the chromosome prefix together with this hg38 file? It seems to, but it is a bit unclear in the documentation and with this issue #15

The sex-check, also gives this output:
```
INFO sex_check
no intervals found for livingox.vcf.gz at X:2781480
```
but also seems to predict the sex anyway.

Thx!

**Comment by brentp** [comment]
yes, as you've found, it should work for hg38 with or without the 'chr' prefix. the warning just means that no samples had coverage at that particular position. this can be ignored.
