### ISSUE TITLE
can ped_check file differentiate parent-child versus sibling pairs?

### ISSUE THREAD

**Issue by wangfan860** [brentp/peddy#73]
Just by looking at the header of the ped_check file, I saw it was evaluating potential discrepancies for parent-child pairs but there was no evaluation of sibling pairs.  Many of the ‘discrepancies’ that appear occur because sample a and sample b are related (~0.5) but are not parent-child.  Most of them are likely siblings.  Is there any way in the file to differentiate between possible problems with incompatibility as parent-child versus being sibling pairs?

**Comment by brentp** [comment]
hi, this is better done using the html. but in the ped_check file sibs will have a rel (derived from pedigree relatinoships) of 0.49 (and arbitrary value to make the differentation between sib-sib and parent-child) while parents will have 0.50. So you can look for scenarios where rel == 0.49 and relatedness < XX. Or vice-versa.

Does that answer your question?

**Comment by wangfan860** [comment]
thank you so much for the quick reply. That definitely helps, i will look into the html. 

Another question is about interpretation of the rel-difference.csv file.  Since all subjects are included in the file, does the level of discrepancy relate to the value shown in that file.  And is there a cutoff indicating potential problems (i.e. level of outlier)? 

Thank you very much!

**Comment by brentp** [comment]
the idea of rel-difference is that if you have a single-sample that is misspecified, it will often cause errors in multiple relations. the rel-difference is the sum of the difference between observed (from the VCF) and expected (from the pedigree file). the assumption is that it makes the most sense to try to correct the samples with the highest difference and often other samples will be resolved in the process.
in practice, we find that it's often more straight-forward to look at the html output, hover on the samples, and figure out what's going on that way.

**Comment by wangfan860** [comment]
Referring to your first reply, do you mean parent-child will have exact 0.5 rel, and siblings <=0.49 ?

**Comment by brentp** [comment]
Sorry, I remembered incorrectly. `rel` is the column for the value estimated from the genotypes. 
You can find sibs and parents by requiring that pedigree_relatedness == 0.5.
With that subset, parent-child pairs will have `pedigree_parents` == True and sibs will have that as false.

If you mean from the estimated values, how to tell sibs from parent-child, well, parent-child pairs will have an ibs0 value that is very close to 0 (maybe 10-20 at most, often less) and sibs will have an ibs0 that is 10 times that high, often over 80.

**Comment by wangfan860** [comment]
It makes sense now! Thank you sooo much for the clear explanation and also for developing this great tool!! It's very handy to use!
