### ISSUE TITLE
peddy sex-check incorrect prediction

### ISSUE THREAD

**Issue by Fazulur** [brentp/peddy#74]
Dear Team,

For some of the female samples, peddy is predicting as "male" . 
I provided vcf & ped to run peddy and it gave me some sample 

command:
peddy sample.vcf sample.ped

## INFO message
**changed sex of samples: sample1 to male in ped**

But sample1 is female as per our records.

And in peddy manual it is mentioned as males should have very few heterozygote calls on the X- chromosome and females should have relatively many. 

Could you please help me to resolve gender mismatch cases? 
Should we go with predicted one or user-proived pedigree as per our records?

Thanks In Advance
Fazulur Rehaman

**Comment by brentp** [comment]
can you share the html generated by peddy?

**Comment by Fazulur** [comment]
Dear Brent,

Thanks a lot for your quick response.
Please find attached html produced by peddy & help me to resolve this.
[peddy-html.zip](https://github.com/brentp/peddy/files/4304862/peddy-html.zip)

Thanks In Advance for your help.
Fazulur Rehaman

**Comment by brentp** [comment]
hi, it's hard to tell decisively from that. It does have a very low rate of hets on the X chromosome.
You can tell the trio is as it should be, but it's hard to tell if the kid  (sample1) is male or female.
You may want to run [somalier](https://github.com/brentp/somalier) as well. It is very similar to peddy, but it will also allow you to look at coverage on the X and Y in order to better determine the sex of the sample.

**Comment by Fazulur** [comment]
Dear Brent,

Thanks for your suggestion. I will run somalier & check.

Thanks & Regards
Fazulur Rehaman

**Comment by athitheo** [comment]
Dear Brent,

I had the same issue recently and I noticed that my newly created vcf files where having 1 instead of 1/1 for homozygous calls on chrX. Could this be the reason and does somalier handle this?

Thanks
Athina

**Comment by brentp** [comment]
The sex check can't work without diploid genotypes. If you tell the caller that a chromosome is haploid when in fact (there is a sample or sex swap and) it's diploid, you hide all of the information that peddy could use to find that problem. 
Well, I suppose it might lead to an abundance of 1 calls but it peddy is designed to accept diploid calls only.

**Comment by athitheo** [comment]
thanks Brentp!
