### ISSUE TITLE
How many Snps used in the PCA ?

### ISSUE THREAD

**Issue by ymavura3** [brentp/peddy#80]
Hi Brent, I am using Peddy to get ancestry from VCF files from RNA-seq samples which have 5-15 million uniquely mapped reads, so the quality is not great. My question is, how do I know how many snps were used in the PCA ? This is quite important in my analysis.
Thanks.
Yusuph.

**Comment by brentp** [comment]
you can look at het_check.csv and look at the sampled_sites column to know how many sites were used in the PCA.
