### ISSUE TITLE
Validity of projected PC in peddy for covariate use

### ISSUE THREAD

**Issue by Dzhan4** [brentp/peddy#87]
Hello, I have a question that I've been struggling with. We used peddy to infer ancestry in our cohort, but also used the projected PCs as covariates to adjust for ancestry (we are not doing GWAS, but rather genetic-clinical association analyses). I recognize that most manuscripts derive their own principal components in their cohort for adjustment. We find that the projected PCs reported in peddy discriminates our cohort well when plotting PC1 and PC2 and corresponds to self-declared ethnicity.

My question is, is it valid to use projected PCs derived from peddy as "principal components of ancestry" for covariate adjustment?

**Comment by brentp** [comment]
Hi, I would think that would be a reasonable thing to do, but you'd want to consult a statistical geneticist.
