### ISSUE TITLE
Inconsistent ancestry prediction of a sample using peddy on a cohort VCF and individual VCF

### ISSUE THREAD

**Issue by anjalijain22** [brentp/peddy#90]
Hi, this is not an issue but more of a question - I'm using peddy on a cohort VCF to predict the ancestry of the samples. Note that I created this cohort VCF by merging individual VCFs together, i.e., they were not joint called. Using the cohort VCF, peddy predicted one sample to be "UNKNOWN" with a probability of 49% but when I ran peddy on the individual VCF the same sample was predicted to be EAS with a probability of 98%.

I'm wondering if you had any insights as to why this may be happening? Does peddy take into account other samples in the cohort VCF as well while making the predictions which could be why there is a discrepancy or could it be because of a difference in the number of sites being sampled? Lastly, is it more reliable to use peddy on individual VCFs for ancestry predictions rather than a cohort VCF?

Thank you in advance for your help with this, I really appreciate it!

**Comment by brentp** [comment]
Hi, you should never use peddy on VCF from merged individual samples as there will never be hom-ref calls. I am surprised there is only 1 sample that changes.
So, it's more reliable to use a cohort VCF, certainly.

**Comment by anjalijain22** [comment]
That makes sense! Thanks very much for your prompt response, I appreciate it!
